site_name: More greetings
repo_url: https://github.com/systopia/de.systopia.moregreetings
theme: material

pages:
- Home: index.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
