site_name: More Greeting Options
site_description: Extension to allow additional, customised greetings
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.moregreetings

theme:
  name: material

nav:
  - Introduction: index.md
  - Basics: basics.md
  - Installation: installation.md
  - Usage: usage.md
  - Example: example.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
